language: python
python:  
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - echo "test"

before_deploy: "echo 'ready?'"
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-east-1"  
  app: "swe1_app"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-east-1-651033129971"
  on:
    branch: master
after_deploy: "echo 'deployed?'"